from utils import references, colors, grids
from utils.terminal import draw, draw_frame, draw_centered, get_window_width_center, get_window_height_center, clear_area


def game_notification(text: str, color: str = colors.WHITE) -> None:
    """Draw a notification.

    In this program a notification is generated by drawing a frame and a text inside it.
    :param text: The text of the notifcation.
    :param color: (optional) The color of the text.

    """
    x, y = draw_frame(4 + (grids.get_size(references.grid_matrice)[0] * 2) + 40, 2, 45, 2)
    draw(text, x + 1, y, color)


def menu_notification(text: str, y_dist: int, color: str = colors.WHITE) -> None:
    """Draw a notification relative to the center of the terminal.

    :param text: The text of the notifcation.
    :param y_dist: distance on y-axis from the heigh center of the terminal.
    :param color: (optional) The color of the text.

     """
    draw_centered(text, y_dist, color)
    draw_frame(get_window_width_center() - (len(text) // 2) - 2, get_window_height_center() + y_dist - 1, len(text) + 4, 2)


def alert(text: str) -> None:
    """Draw a notification with the dark red color.

    :param text: The text of the notifcation.

    """
    game_notification(text, colors.DARK_RED)


def warn(text: str) -> None:
    """Draw a notification with the dark yellow color.

    :param text: The text of the notifcation.

    """
    game_notification(text, colors.DARK_YELLOW)


def clear_notification() -> None:
    """Clear the area of game notifications."""
    clear_area(4 + (grids.get_size(references.grid_matrice)[0] * 2) + 40, 2, 46, 4)
